
package org.russianpost.operationhistory;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OperationHistory", targetNamespace = "http://russianpost.org/operationhistory", wsdlLocation = "http://voh.russianpost.ru:8080/niips-operationhistory-web-ml/OperationHistory?WSDL")
public class OperationHistoryClient
    extends Service
{

    private final static URL OPERATIONHISTORY_WSDL_LOCATION;
    private final static WebServiceException OPERATIONHISTORY_EXCEPTION;
    private final static QName OPERATIONHISTORY_QNAME = new QName("http://russianpost.org/operationhistory", "OperationHistory");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://voh.russianpost.ru:8080/niips-operationhistory-web-ml/OperationHistory?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OPERATIONHISTORY_WSDL_LOCATION = url;
        OPERATIONHISTORY_EXCEPTION = e;
    }

    public OperationHistoryClient() {
        super(__getWsdlLocation(), OPERATIONHISTORY_QNAME);
    }

    public OperationHistoryClient(WebServiceFeature... features) {
        super(__getWsdlLocation(), OPERATIONHISTORY_QNAME, features);
    }

    public OperationHistoryClient(URL wsdlLocation) {
        super(wsdlLocation, OPERATIONHISTORY_QNAME);
    }

    public OperationHistoryClient(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OPERATIONHISTORY_QNAME, features);
    }

    public OperationHistoryClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OperationHistoryClient(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OperationHistoryInterface
     */
    @WebEndpoint(name = "OperationHistory")
    public OperationHistoryService getOperationHistoryService() {
        return super.getPort(new QName("http://russianpost.org/operationhistory", "OperationHistory"), OperationHistoryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OperationHistoryInterface
     */
    @WebEndpoint(name = "OperationHistory")
    public OperationHistoryService getOperationHistory(WebServiceFeature... features) {
        return super.getPort(new QName("http://russianpost.org/operationhistory", "OperationHistory"), OperationHistoryService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OPERATIONHISTORY_EXCEPTION!= null) {
            throw OPERATIONHISTORY_EXCEPTION;
        }
        return OPERATIONHISTORY_WSDL_LOCATION;
    }

}
