
package org.russianpost.operationhistory;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "PostalOrderEventsForMailFault", targetNamespace = "http://www.russianpost.org/RTM/DataExchangeESPP/Data")
public class PostalOrderEventsForMailFault
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 7253103188093523712L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private org.russianpost.rtm.dataexchangeespp.data.PostalOrderEventsForMailFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public PostalOrderEventsForMailFault(String message, org.russianpost.rtm.dataexchangeespp.data.PostalOrderEventsForMailFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public PostalOrderEventsForMailFault(String message, org.russianpost.rtm.dataexchangeespp.data.PostalOrderEventsForMailFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.russianpost.rtm.dataexchangeespp.data.PostalOrderEventsForMailFault
     */
    public org.russianpost.rtm.dataexchangeespp.data.PostalOrderEventsForMailFault getFaultInfo() {
        return faultInfo;
    }

}
